version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: springboot-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      # this overrides url in application properties
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/{dbName}
volumes:
  mongodb_data: